# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('temp', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.FileField(default=0,
                                   upload_to='temp/media/documents/<django.db.models.fields.CharField><built-in function id>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
